### ISSUE TITLE
TODO: Store

### ISSUE THREAD

**Issue by jordanlambrecht** [jordanlambrecht/pb-oct-2022#30]
**Global**
- [x] Move shopping cart button to it's own component. I couldn't get it. (@henrysipp )
- [x] Maybe add PB's logo to headers? (@jordanlambrecht )
- [x] Maaaaaybe add google tags if there's time (@jordanlambrecht )
- [x] Deploy to digitalocean (@jordanlambrecht)

**Store Page**
- [x] Add hoodie and sticker pack (@jordanlambrecht )

**Product Page**
- [x] Add input validation for Pay What You Want. Currently users can manually enter a number less than the minimum required amount and it will be accepted (@henrysipp )
- [x] Hook entered Pay What You Want price to product price in cart (@henrysipp )
- [x] Hook variant selection to product item in cart (@henrysipp )
- [x] Disable Add to Cart if specific variant is sold out ~~low priority, we're not doing variant inventory for now~~ (@henrysipp )
- [x] Disable Add To Cart if product is sold out (@jordanlambrecht )
- [x] Switch permalinks to pretty structure ~low priority~ (@henrysipp )

**Cart**
- [x] Wrap item name and item photo in a Link and redirect back to product page (@henrysipp )
- [x] Fix styling alignment issue with 'pony up' button (@jordanlambrecht )
- [x] split products into individual line items if they have different variants (@henrysipp )
- [x] add subtext on line items of which variant they are, if any. (@henrysipp for functionality, @jordanlambrecht for styling)
- [x] BUG: If a user selects 'extra small' variant, variant name does not display in cart. I can probably fiddle around with this one to figure out why. I'm guessing it has something to do with getting/setting the initial variant. There's bigger fish to fry, and we can deduce that no variant name = extra small. (@henrysipp or @jordanlambrecht )

**Checkout**
- [x] Stripe payment gateway (@henrysipp )
- [x] Redirect to order confirmation. on successful capture (@henrysipp)
- [x] General page styling and layout (@jordanlambrecht )

**Order Confirmation**
_nothing! done._
