### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jordanlambrecht** [jordanlambrecht/pb-oct-2022#7]
**About Page**
- [ ] Add Lightbox onto 'family photos' slider

**Backend**
- [ ] Localize chevron icon

**Blog Posts**
- [ ] Comment section
- [ ] Mobile Responsiveness

**Careers**
- [ ] Pull 'favorite band' from application and display it on submission conformation page (line 20 in /pages/careers/careers-submitted)

**Footer**

- [ ] Croissant email system
- [ ] Mobile Responsiveness

**Login**
- [ ] Style form
- [ ] randomize displayed hero image every page load (low priority)

**Navigation**
- [ ] Implement hamburger nav
- [ ] Create alternative white version for darker backgrounds

**Styling**

- [ ] Explore possible use of [tailwind typography](https://github.com/tailwindlabs/tailwindcss-typography) plugin
- [ ] Figure out how to switch over to SASS? I tried combing through the Vite docs but couldn't figure out how @henrysipp
